(() => {
  const E=window.SimEngine,W=window.SimWorld,SP=window.SimSpatial;if(!E||!W||!SP)return;
  const VERSION=W.INTERRUPTION_SCHEMA_VERSION||'11.12.3-replan-preemption';
  const REPLAN_ACTION_BY_INTENT={
    satisfyHunger:'eat',drinkWater:'drinkWater',drinkAlcohol:'drinkAlcohol',recoverFatigue:'rest',sleep:'sleep',
    socialize:'talk',interactWithAnimal:'petAnimal',seekSocialContact:'seekHuman',removeHazard:'cleanFloor',groom:'groom',explore:'wander'
  };
  const REPLAN_SUPPORTED=new Set([...Object.keys(REPLAN_ACTION_BY_INTENT),'respondSocialBid']);
  const EMERGENCY_PREEMPTIBLE=new Set(['wander','talk','petAnimal','seekHuman','cleanFloor','groom','rest']);
  const MAX_REPLAN_ATTEMPTS=3;
  const CARRY_WAIT_TICKS=2,CARRY_WAIT_BASE_UTILITY=20,CARRY_NEUTRAL_PLACEMENT_BASE_UTILITY=45,CARRY_NO_PLACEMENT_WAIT_BONUS=30;
  const carryingDecisionOptionProviders=[];
  const clone=v=>v==null?v:JSON.parse(JSON.stringify(v));
  function registerCarryingDecisionOptionProvider(id,provider,order=0){if(!id||typeof provider!=='function')throw new Error('carrying decision option provider requires id + function');if(carryingDecisionOptionProviders.some(x=>x.id===id))throw new Error(`duplicate carrying decision option provider: ${id}`);const entry={id,provider,order:Number(order)||0};carryingDecisionOptionProviders.push(entry);carryingDecisionOptionProviders.sort((a,b)=>a.order-b.order||a.id.localeCompare(b.id));return entry;}
  function listCarryingDecisionOptionProviders(){return carryingDecisionOptionProviders.map(({id,order})=>({id,order}));}
  function actionKind(a){return E.actionKind?E.actionKind(a?.action):a?.action?.kind||null;}
  function clearAgentReservations(st,a){for(const [key,owner] of Object.entries({...st.reservations}))if(owner===a.id)delete st.reservations[key];}
  function dropHeld(st,a){if(!a.held)return;const c=st.containers?.[a.held];if(c)c.position={...a.position};a.held=null;}
  function cleanupForInterruption(st,a){clearAgentReservations(st,a);dropHeld(st,a);a.action=null;}
  function interactionTraversalCost(st,a,target,affordance='default'){if(typeof SP.bestInteractionPositionResult==='function')return SP.bestInteractionPositionResult(st,a,target,affordance)?.traversalCost??Infinity;const goal=SP.bestInteractionPosition(st,a,target,affordance);return goal?(SP.traversalCost?.(st,a,goal)??SP.pathDistance(st,a,goal)):Infinity;}
  function nearestAgent(st,a,kind,{awakeOnly=false}={}){return Object.values(st.agents||{}).filter(x=>x.id!==a.id&&!x.offMap&&x.kind===kind&&(!awakeOnly||!E.isSleeping(x))).map(x=>({x,d:interactionTraversalCost(st,a,{kind:'agent',id:x.id},'social')})).filter(x=>Number.isFinite(x.d)).sort((p,q)=>p.d-q.d||String(p.x.id).localeCompare(String(q.x.id)))[0]?.x||null;}
  function nearestDrinkContainer(st,a,resource){return Object.values(st.containers||{}).filter(c=>c.canDrinkFrom&&(c.contents?.[resource]||0)>.05).map(c=>{const d=interactionTraversalCost(st,a,{kind:'object',id:c.id},'drinkFrom');return Number.isFinite(d)?{c,d}:null;}).filter(Boolean).sort((p,q)=>p.d-q.d||String(p.c.id).localeCompare(String(q.c.id)))[0]?.c||null;}
  function buildAction(st,a,actionKindValue,{targetAgent=null}={}){
    if(!E.buildAction)return null;
    const choice={id:actionKindValue};
    if(targetAgent)choice.targetAgent=targetAgent;
    if((actionKindValue==='drinkWater'||actionKindValue==='drinkAlcohol')&&a.kind==='cat'){
      const resource=actionKindValue==='drinkWater'?'water':'alcohol',src=nearestDrinkContainer(st,a,resource);if(!src)return null;choice.targetObject=src.id;
    }
    return E.buildAction(a,choice);
  }
  function bindActionToIntent(a,intent,action){if(!action)return false;action.intentId=intent.id;intent.lifecycle='actionBound';a.action=action;a.activeIntent=intent;return true;}
  function responseTargetForIntent(st,intent){if(intent?.kind!=='respondSocialBid'||intent.source?.type!=='socialBid')return null;const bid=E.bidEvent?.(st,intent.source.bidId);if(!bid)return null;const target=st.agents?.[bid.data?.bidFrom];return target&&!target.offMap?target.id:null;}
  function planOpenIntent(st,a){const intent=a.activeIntent;if(a.action||!intent||intent.lifecycle!=='open'||intent.kind==='awaitResponse')return false;if(!REPLAN_SUPPORTED.has(intent.kind))return false;let kind=REPLAN_ACTION_BY_INTENT[intent.kind],targetAgent=null;if(intent.kind==='respondSocialBid'){kind='petAnimal';targetAgent=responseTargetForIntent(st,intent);if(!targetAgent||!E.canPetAnimal?.(a,st.agents?.[targetAgent]))return false;}const priorEvidence=a.decisionEvidence,priorMatches=priorEvidence?.intentId===intent.id,priorDecisionId=priorMatches?priorEvidence.id:null,action=buildAction(st,a,kind,{targetAgent});if(action&&bindActionToIntent(a,intent,action)){const count=intent.replanCount||0,inherited=priorMatches?(priorEvidence.contributors||[]).filter(c=>c?.role!=='targetSelection'&&c?.kind!=='socialTarget'):(E.decisionContributorsForAction?.(a,kind)||[]);E.adoptDecisionEvidence?.(st,a,action,{source:{type:'hardReplan',tick:st.tick,intentKind:intent.kind,replanCount:count},contributors:inherited,priorDecisionId});E.addEvent(`${a.name}依原本的「${E.intentLabel?.(intent)||intent.kind}」重新安排${E.ZH?.[kind]||kind}。`,'system',[],{actor:a.id,action:'actionReplanned',intentId:intent.id,intentKind:intent.kind,nextActionKind:kind,replanCount:count,position:E.positionRef(a.position)});return true;}intent.replanAttempts=(intent.replanAttempts||0)+1;if(intent.replanAttempts>=MAX_REPLAN_ATTEMPTS){E.addEvent(`${a.name}暫時找不到能完成「${E.intentLabel?.(intent)||intent.kind}」的方案，停止這個短期意圖。`,'normal',[],{actor:a.id,action:'intentAbandon',intentId:intent.id,intentKind:intent.kind,replanCount:intent.replanCount||0,position:E.positionRef(a.position)});a.activeIntent=null;}return false;}
  function intentStillValid(st,a,intent){if(!intent)return false;const n=a.needs||{};switch(intent.kind){case'satisfyHunger':return (n.hunger||0)>18&&!!E.canSatisfyHunger?.(a);case'drinkWater':return (n.thirst||0)>18&&!!E.canDrinkResource?.(a,'water');case'drinkAlcohol':return (n.thirst||0)>18&&!!E.canDrinkResource?.(a,'alcohol');case'recoverFatigue':return (n.fatigue||0)>22;case'sleep':return (n.sleepNeed||0)>=(E.sleepProfile?.(a)?.minimumSleepNeed??28);case'socialize':return (n.social||0)>10&&!!nearestAgent(st,a,'human',{awakeOnly:true});case'interactWithAnimal':return a.kind==='human'&&!!E.nearestPettableAnimal?.(a);case'seekSocialContact':return E.isAnimalAgent?.(a)&&(n.social||0)>10&&!!nearestAgent(st,a,'human');case'removeHazard':{const t=SP.wettestTile(st);return !!t&&SP.tileLiquidAmount(t)>.2;}case'groom':return (n.groomingNeed||0)>15||Object.values(a.contacts?.paws||{}).some(v=>v>.05);case'explore':return true;case'respondSocialBid':{const targetId=responseTargetForIntent(st,intent);return !!targetId&&!!E.canPetAnimal?.(a,st.agents?.[targetId]);}default:return false;}}
  function emergencyChoice(st,a){const candidates=[];if((a.needs?.thirst||0)>=94)candidates.push({need:'thirst',value:a.needs.thirst,intentKind:'drinkWater',actionKind:'drinkWater'});if((a.needs?.hunger||0)>=94)candidates.push({need:'hunger',value:a.needs.hunger,intentKind:'satisfyHunger',actionKind:'eat'});const minSleep=E.sleepProfile?.(a)?.minimumSleepNeed??28;if((a.needs?.sleepNeed||0)>=96&&(a.needs.sleepNeed||0)>=minSleep)candidates.push({need:'sleepNeed',value:a.needs.sleepNeed,intentKind:'sleep',actionKind:'sleep'});return candidates.sort((x,y)=>y.value-x.value)[0]||null;}
  function canStartEmergency(st,a,c){return !!buildAction(st,a,c.actionKind);}
  function startEmergency(st,a,c){const priorActionKind=actionKind(a),priorIntent=clone(a.activeIntent),priorDecisionId=E.currentDecisionEvidence?.(a)?.id||null,priorLabel=priorActionKind?(E.ZH?.[priorActionKind]||priorActionKind):priorIntent?`「${E.intentLabel?.(priorIntent)||priorIntent.kind}」`:'目前安排';cleanupForInterruption(st,a);a.activeIntent=null;const action=buildAction(st,a,c.actionKind);if(!action)return false;const intent=E.createIntent?E.createIntent(st,a,action):{id:`intent:${a.id}:${st.tick}:${c.intentKind}`,kind:c.intentKind,createdTick:st.tick,lifecycle:'actionBound',source:{type:'emergency',tick:st.tick}};intent.kind=c.intentKind;intent.lifecycle='actionBound';intent.source={type:'emergency',need:c.need,value:c.value,tick:st.tick};action.intentId=intent.id;a.action=action;a.activeIntent=intent;E.adoptDecisionEvidence?.(st,a,action,{source:{type:'emergency',tick:st.tick,intentKind:c.intentKind,need:c.need},contributors:[{kind:'need',key:c.need,role:'emergency',value:c.value}],priorDecisionId});E.addEvent(`${a.name}因${E.ZH?.[c.need]||c.need}過於迫切，中斷${priorLabel}，改先處理緊急需求。`,'warn',[],{actor:a.id,action:'intentPreempt',priorActionKind:priorActionKind||null,nextActionKind:c.actionKind,intentId:intent.id,intentKind:intent.kind,emergencyNeed:c.need,emergencyValue:c.value,priorIntentId:priorIntent?.id||null,position:E.positionRef(a.position)});return true;}
  function applyEmergencyPreemption(st){for(const a of Object.values(st.agents||{})){const kind=actionKind(a),openIntent=!a.action&&a.activeIntent?.lifecycle==='open',occupancyWait=kind==='sleep'&&a.action?.phase==='conflictWait';if(kind&&!occupancyWait&&!EMERGENCY_PREEMPTIBLE.has(kind))continue;if(!kind&&!openIntent)continue;const c=emergencyChoice(st,a);if(!c)continue;if(a.activeIntent?.kind===c.intentKind)continue;if(!canStartEmergency(st,a,c))continue;startEmergency(st,a,c);}}
  function newEventsSince(st,marker){const out=[];for(const e of st.events||[]){if(marker&&e.id===marker)break;out.push(e);}return out;}
  function recoverAbortedIntents(st,before,newEvents){const abortByActor=new Map();for(const e of newEvents)if(e.data?.action==='abort'&&e.data?.actor)abortByActor.set(e.data.actor,e);for(const [agentId,snap] of before){const a=st.agents?.[agentId],abort=abortByActor.get(agentId);if(!a||!abort||a.action||a.activeIntent)continue;const intent=snap.intent;if(!intent||intent.lifecycle!=='actionBound'||!REPLAN_SUPPORTED.has(intent.kind))continue;if(!intentStillValid(st,a,intent))continue;intent.lifecycle='open';intent.replanCount=(intent.replanCount||0)+1;intent.lastReplanTick=st.tick;intent.replanAttempts=0;a.activeIntent=intent;E.addEvent(`${a.name}的${E.ZH?.[snap.actionKind]||snap.actionKind}方案失效，但「${E.intentLabel?.(intent)||intent.kind}」仍成立，準備重新規劃。`,'normal',[abort.id],{actor:a.id,action:'replanAction',priorActionKind:snap.actionKind,intentId:intent.id,intentKind:intent.kind,replanCount:intent.replanCount,position:E.positionRef(a.position)});}}
  function snapshotLiveActions(st){const out=new Map();for(const a of Object.values(st.agents||{}))if(a.action&&a.activeIntent)out.set(a.id,{actionKind:actionKind(a),intent:clone(a.activeIntent)});return out;}
  function planOpenIntents(st){for(const a of Object.values(st.agents||{}))planOpenIntent(st,a);}
  function carryingReplanTrigger(st,a){
    const A=window.SimAgentCarry,relation=A?.relationForCarrier?.(st,a),p=a?.action;if(!relation||p?.kind!=='carryAgent'||p.phase!=='recoveryBlocked')return null;
    const waitUntil=Number(p.carryingWaitUntilTick);if(Number.isFinite(waitUntil)&&st.tick<waitUntil)return null;
    return {reason:Number.isFinite(waitUntil)?'wait-cadence':'placement-invalidation',relation,priorAction:p};
  }
  function normalizeCarryingPlacement(target){if(!target||!['floor','slot'].includes(target.kind))return null;return target.kind==='floor'?{kind:'floor',position:clone(target.position)}:{kind:'slot',id:target.id,posture:target.posture||null};}
  function carryingDecisionOptions(st,a,trigger){
    const A=window.SimAgentCarry,relation=trigger?.relation||A?.relationForCarrier?.(st,a);if(!relation)return [];const out=[];
    for(const entry of carryingDecisionOptionProviders){const value=entry.provider(st,a,{relation:clone(relation),trigger:trigger?.reason||null})??[];for(const option of Array.isArray(value)?value:[value]){const targetPlacement=normalizeCarryingPlacement(option?.targetPlacement);if(!targetPlacement||!Number.isFinite(option?.score))continue;out.push({kind:'placement',targetPlacement,score:Number(option.score),contributors:clone(option.contributors||[]),providerId:entry.id});}}
    const neutral=normalizeCarryingPlacement(A?.recoveryPlacement?.(st,a,{radius:A.RECOVERY_RADIUS}));if(neutral)out.push({kind:'placement',targetPlacement:neutral,score:CARRY_NEUTRAL_PLACEMENT_BASE_UTILITY,contributors:[{kind:'carryingState',key:'neutralSafetyPlacement',role:'placementFallback',relationId:relation.id}],providerId:'agentCarry.neutralSafety'});
    const hasPlacement=out.some(x=>x.kind==='placement');out.push({kind:'wait',score:CARRY_WAIT_BASE_UTILITY+(hasPlacement?0:CARRY_NO_PLACEMENT_WAIT_BONUS),contributors:[{kind:'carryingState',key:'stationaryWait',role:'fallback',relationId:relation.id,noPlacement:!hasPlacement}]});
    return out.sort((x,y)=>y.score-x.score||x.kind.localeCompare(y.kind)||JSON.stringify(x.targetPlacement||null).localeCompare(JSON.stringify(y.targetPlacement||null)));
  }
  function buildCarryingReplacement(st,a,trigger,choice){
    const relation=trigger?.relation,prior=trigger?.priorAction;if(!relation||!prior||!choice)return null;const targetPlacement=choice.kind==='placement'?normalizeCarryingPlacement(choice.targetPlacement):normalizeCarryingPlacement(prior.targetPlacement);if(!targetPlacement)return null;
    const action=E.buildAction?.(a,{id:'carryAgent',targetAgent:relation.carriedAgentId,targetPlacement,originalConflictSlotId:prior.originalConflictSlotId||null,relocationContext:prior.relocationContext||null,relocationOutcome:'failed',carryEstablishedEventId:prior.carryEstablishedEventId||null});if(!action)return null;
    action.intentId=prior.intentId||a.activeIntent?.id||null;action.recoveryMode=true;action.relocationOutcome='failed';action.relocationFailedEventId=prior.relocationFailedEventId||null;action.carryEstablishedEventId=prior.carryEstablishedEventId||null;action.carryingDecisionKind=choice.kind;
    if(choice.kind==='wait'){action.phase='recoveryBlocked';action.carryingWaitUntilTick=st.tick+CARRY_WAIT_TICKS;action.recoveryRetryAtTick=action.carryingWaitUntilTick;}
    return action;
  }
  function applyCarryingReplan(st,a){
    const trigger=carryingReplanTrigger(st,a);if(!trigger)return false;const options=carryingDecisionOptions(st,a,trigger),pick=options[0];if(!pick)return false;const priorDecisionId=E.currentDecisionEvidence?.(a)?.id||a.action?.decisionId||null,next=buildCarryingReplacement(st,a,trigger,pick);if(!next)return false;
    const intent=a.activeIntent;if(intent)intent.lifecycle='actionBound';a.action=next;const evidence=E.adoptDecisionEvidence?.(st,a,next,{source:{type:'carryingReplan',tick:st.tick,intentKind:intent?.kind||null,trigger:trigger.reason,decisionKind:pick.kind,providerId:pick.providerId||null},contributors:pick.contributors||[],utility:pick.score,priorDecisionId});
    E.addEvent(`${a.name}抱持中重新評估安全放置方案，決定${pick.kind==='wait'?'先原地等待':'改採新的放置位置'}。`,'normal',[trigger.priorAction.relocationFailedEventId].filter(Boolean),{actor:a.id,target:trigger.relation.carriedAgentId,action:'carryingReplanDecision',relationId:trigger.relation.id,trigger:trigger.reason,decisionKind:pick.kind,decisionId:evidence?.id||null,priorDecisionId:priorDecisionId||null,providerId:pick.providerId||null,position:E.positionRef(a.position)});return true;
  }
  function applyCarryingReplans(st){for(const a of Object.values(st.agents||{}))applyCarryingReplan(st,a);}
  function prepareTick(st){applyEmergencyPreemption(st);applyCarryingReplans(st);planOpenIntents(st);return {before:snapshotLiveActions(st),marker:st.events?.[0]?.id||null};}
  function settleTick(st,snap){if(!snap)return;const newEvents=newEventsSince(st,snap.marker);recoverAbortedIntents(st,snap.before,newEvents);E.reconcileIntents?.(st);}

  if(!E.registerRuntimeHook)throw new Error('systems/intent/replanning.js requires runtime-hook-pipeline.js');
  E.registerRuntimeHook('beforeTick','intent.replan-preemption',(ctx)=>{ctx.locals.intentV1123=prepareTick(E.getState());},800);
  E.registerRuntimeHook('afterTick','intent.recover-aborts',(ctx)=>settleTick(E.getState(),ctx.locals.intentV1123),400);

  Object.assign(E,{INTERRUPTION_SCHEMA_VERSION:VERSION,REPLAN_SUPPORTED,EMERGENCY_PREEMPTIBLE,MAX_REPLAN_ATTEMPTS,CARRY_WAIT_TICKS,CARRY_WAIT_BASE_UTILITY,CARRY_NEUTRAL_PLACEMENT_BASE_UTILITY,CARRY_NO_PLACEMENT_WAIT_BONUS,registerCarryingDecisionOptionProvider,listCarryingDecisionOptionProviders,carryingDecisionOptions,applyCarryingReplan,intentStillValid,planOpenIntent,emergencyChoice});
})();
